server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.34.221:3306/jiuair_oa?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: jiuair_cloud
    password: 123456
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: oafile


#mybatis plus
mybatis-plus:
  typeAliasesPackage: com.jiuair.cloud.oatools.entity
  mapper-locations: classpath:mapper/*.xml